apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cms
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: adeyomola/wordpress
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              value: "${db_user}"
            - name: DB_PASSWORD
              value: "${db_password}"
            - name: DB_HOST
              value: db-service.cms.svc.cluster.local
            - name: DB_NAME
              value: "${db_name}"
