variables:
  - group: cms
jobs:
  - job:
      Destroy
      # Destroy App
    steps:
      - task: DownloadSecureFile@1
        name: ansiblePass
        displayName: "Download Ansible Vault Password File"
        inputs:
          secureFile: ".pass.txt"
      - bash: |
          export ANSIBLE_VAULT_PASSWORD_FILE=$(ansiblePass.secureFilePath)
          terraform init
          terraform apply -auto-approve
        displayName: Convert Template Files
        workingDirectory: ansible
      - task: Bash@3
        displayName: Destroy App
        inputs:
          targetType: inline
          script: |
            terraform init
            terraform destroy -auto-approve
          workingDirectory: deploy
        env:
          AWS_ACCESS_KEY_ID: $(access_key_id)
          AWS_SECRET_ACCESS_KEY: $(secret_access_key)
          AWS_DEFAULT_REGION: $(REGION)
          TF_VAR_db_user: $(USERNAME)
          TF_VAR_db_password: $(USERNAME)
          TF_VAR_db_name: $(DB_NAME)
          TF_VAR_db_port: 3306
      # Destroy Logging
      - task: Bash@3
        displayName: Destroy Elastic
        retryCountOnTaskFailure: 1
        inputs:
          targetType: inline
          script: |
            terraform init
            terraform destroy -auto-approve
          workingDirectory: logging
        env:
          AWS_ACCESS_KEY_ID: $(access_key_id)
          AWS_SECRET_ACCESS_KEY: $(secret_access_key)
          AWS_DEFAULT_REGION: $(REGION)
      # Destroy Monitoring
      - task: Bash@3
        displayName: Destroy Prometheus and Grafana
        inputs:
          targetType: inline
          script: |
            terraform init
            terraform destroy -auto-approve
          workingDirectory: monitoring
        env:
          AWS_ACCESS_KEY_ID: $(access_key_id)
          AWS_SECRET_ACCESS_KEY: $(secret_access_key)
          AWS_DEFAULT_REGION: $(REGION)
      # Destroy Ingress Controller
      - task: Bash@3
        displayName: Destroy Ingress Controller
        inputs:
          targetType: inline
          script: |
            terraform init
            terraform destroy -auto-approve
          workingDirectory: alb
        env:
          AWS_ACCESS_KEY_ID: $(access_key_id)
          AWS_SECRET_ACCESS_KEY: $(secret_access_key)
          AWS_DEFAULT_REGION: $(REGION)
          TF_VAR_account_id: $(account_id)
        # Destroy SSL Certificate
      - task: Bash@3
        displayName: Destroy SSL Certificate
        inputs:
          targetType: inline
          script: |
            terraform init
            terraform destroy -auto-approve
          workingDirectory: ssl
        env:
          AWS_ACCESS_KEY_ID: $(access_key_id)
          AWS_SECRET_ACCESS_KEY: $(secret_access_key)
          AWS_DEFAULT_REGION: $(REGION)
          TF_VAR_email: $(email)
        # Destroy EKS Cluster
      - task: Bash@3
        displayName: Destroy EKS
        inputs:
          targetType: inline
          script: |
            terraform init
            terraform destroy -auto-approve
          workingDirectory: provision
        env:
          AWS_ACCESS_KEY_ID: $(access_key_id)
          AWS_SECRET_ACCESS_KEY: $(secret_access_key)
          AWS_DEFAULT_REGION: $(REGION)
